### ISSUE TITLE
Launching from the folder

### ISSUE THREAD

**Issue by oleedd** [ChunshengZhao/feedingbottle#1]
How to launch the lastest version from the folder in Wifislax 4.12 ?

**Comment by ChunshengZhao** [comment]
Do you have an error message?

**Comment by oleedd** [comment]
Yes. If I try to open fl file by some commands (sudo, bash), it shows that many strings have errors. It doesn't open as sh files.
But I don't know commands to open this fl type correctly from the folder. There is installed version 3.2 in the latest Wifislax 4.12. But I want to open (not to install) the lastest version from the folder. Please suggest correct commands for opening fl file.

**Comment by oleedd** [comment]
If to use:
fluid -c feedingbottle.fl
it shows:
feedingbottle.fl:2: unknown version '1.0304'

**Comment by ChunshengZhao** [comment]
Please try the new version of FLTK (fluid), or you can compile under KALI and try to run in Wifislax.

**Comment by oleedd** [comment]
How to install the latest fluid from the folder (not directly from internet)?
"or you can compile under KALI and try to run in Wifislax"
I don't know how to do that. Maybe you have already compiled version?

**Comment by oleedd** [comment]
How to install the latest fluid from a folder or a file (not directly from internet)?
"or you can compile under KALI and try to run in Wifislax"
I don't know how to do that. Maybe you have already compiled version?

**Comment by oleedd** [comment]
How to install the latest fluid from a folder or a file (not directly from internet)?
"or you can compile under KALI and try to run in Wifislax"
I don't know how it will look and where to find it after compiling under KALI. Will it be in the same folder? Maybe you have already compiled version? It is better for me if it may work without updating fluid in Wifislax.

**Comment by oleedd** [comment]
How to install the latest fluid from a folder or a file (not directly from internet)?
"or you can compile under KALI and try to run in Wifislax"
I don't know how it will look and where to find it after compiling under KALI. Will it be in the same folder? Maybe you have already compiled version (if so it is very good)? It is better for me if it may work without updating fluid in Wifislax.

**Comment by oleedd** [comment]
How to install the latest fluid from a folder or a file (not directly from internet)?
"or you can compile under KALI and try to run in Wifislax"
I don't know how it will look and where to find it after compiling under KALI. Will it be in the same folder? Maybe you have already compiled version (if so it is very good)? It is much better for me if it may work without updating fluid in Wifislax.

**Comment by ChunshengZhao** [comment]
First of all, the current version of FeedingBottle is written specifically for KALI, and only supports English system, I found wifislax is Spanish;

secondly, I am in China, I tried to download wifislax64-1.0-final.iso, but found that the speed is very slow.

The binaries in the attachment are compiled under KALI-x64.
[feedingbottle.tar.gz](https://github.com/ChunshengZhao/feedingbottle/files/2231898/feedingbottle.tar.gz)

file feedingbottle/feedingbottle
feedingbottle/feedingbottle: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=e6a0993cc576928de986c74a32d95e79381f25a0, with debug_info, not stripped

**Comment by oleedd** [comment]
Each Wifislax version also has English interface (need to change on the first page after booting).
This is fast link for the latest 4.12 version which I use.
https://drive.google.com/open?id=1xHjziBrZighZWH83CgRPxTTn7Fo-dk1O

**Comment by ChunshengZhao** [comment]
In China, it is impossible to visit Google. I am downloading, just very slow(http://www.mediafire.com/file/25rsmyz449g2csc/wifislax64-1.0-final.iso).

**Comment by oleedd** [comment]
Please try this link:
https://www.multcloud.com/action/share!downloadShare?drives.cloudType=59eqxFtENNKLZnM2T6HOHw%3D%3D&drives.tokenId=bb61ce1380244933bf82b1684ae90fcc&drives.fileId=hqXl0hPpb9449qNeh1ukJXND5rCprzn%2BaugHFhQPyNfpaFU4NmT5k8dW%2FdtrAXXD&drives.fileName=wifislax-4-12-final_vmware_edition.iso&drives.fileSize=1864116224&shareId=2ace171e-cd7d-4122-9e9f-a7ff868c0531
For me mediafire link has good speed - 1 megabyte/sec.

**Comment by oleedd** [comment]
New very fast link:
http://srv5.debgen.fr/srv1/?file=mega_577f9d15b9

**Comment by oleedd** [comment]
New high speed links:
http://de.fakirdebrid.net:8080/MEGA/free/files/PremiumZEN.Com_wifislax-4-12-final_vmware_edition.iso
http://srv5.debgen.fr/srv1/?file=mega_577f9d15b9   (after claudflare captcha)

**Comment by ChunshengZhao** [comment]
Edit feedingbottle.fl, delete line : version 1.0304.
I don't know about this system, and the last work can only be done by you.

**Comment by oleedd** [comment]
Wifislax is based on Porteus.
I deleted the string. After this already no that error message about unknown version.
I launched with this command. But many other strange windows open. And can't press program buttons.
![default](https://user-images.githubusercontent.com/36125949/43309570-c951b6fc-918d-11e8-880e-34e160b4ed01.jpg)
Some other commands to try?

**Comment by ChunshengZhao** [comment]
#fluid -c feedingbottle.fl
#fltk-config --compile feedingbottle.cxx
#./feedingbottle

**Comment by oleedd** [comment]
wifislax ~ # fltk-config --compile feedingbottle.cxx
g++ -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libdrm -I/usr/include/libpng16 -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o 'feedingbottle' 'feedingbottle.cxx' /usr/lib/libfltk.a -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
g++: error: /usr/lib/libfltk.a: No such file or directory

Maybe there is a way just to launch cxx file?

**Comment by ChunshengZhao** [comment]
![20180727193234](https://user-images.githubusercontent.com/9263377/43318605-fd5da6f4-91d3-11e8-8158-6c6062d8de82.png)

**Comment by oleedd** [comment]
wifislax ~ # /mnt/sdb1/feedingbottle/feedingbottle
bash: /mnt/sdb1/feedingbottle/feedingbottle: cannot execute binary file: Exec format error

I have a compiled version. So just need to somehow launch it.

**Comment by ChunshengZhao** [comment]
https://stackoverflow.com/questions/35954745/where-can-i-find-libfltk-a

**Comment by oleedd** [comment]
wifislax ~ # file /mnt/sdb1/feedingbottle/feedingbottle
/mnt/sdb1/feedingbottle/feedingbottle: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e6a0993cc576928de986c74a32d95e79381f25a0, not stripped

So I have this. But after this no launch.

**Comment by oleedd** [comment]
wifislax ~ # file /mnt/sdb1/feedingbottle/feedingbottle
/mnt/sdb1/feedingbottle/feedingbottle: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e6a0993cc576928de986c74a32d95e79381f25a0, not stripped

So I have this (almost the same as on your screenshot). But after this no launch. What to do next?

**Comment by oleedd** [comment]
wifislax ~ # file /mnt/sdb1/feedingbottle/feedingbottle
/mnt/sdb1/feedingbottle/feedingbottle: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e6a0993cc576928de986c74a32d95e79381f25a0, not stripped

So I have this (almost the same as on your screenshot). But after this no launch. What to do next?

If just to use this, then an error.
wifislax ~ # /mnt/sdb1/feedingbottle/feedingbottle
bash: /mnt/sdb1/feedingbottle/feedingbottle: cannot execute binary file: Exec format error

Maybe I have 32 bit Wifislax. I don't know exactly. Maybe this is the reason of the error.

**Comment by ChunshengZhao** [comment]
1: fltk
wget http://fltk.org/pub/fltk/1.3.4/fltk-1.3.4-2-source.tar.gz
tar xzf fltk-1.3.4-2-source.tar.gz
cd fltk-1.3.4-2
./configure
make && make install

2: aircrack-ng
git clone https://github.com/aircrack-ng/aircrack-ng
./autogen.sh
make && make install

3: feedingbottle
git clone https://github.com/ChunshengZhao/feedingbottle
cd feedingbottle
fluid -c feedingbottle.fl
fltk-config --compile feedingbottle.cxx
./feedingbottle

![wifislax64-1 0-final-2018-07-28-10-56-56](https://user-images.githubusercontent.com/9263377/43352397-6af4adf8-9255-11e8-8965-33b4a297448c.png)

**Comment by oleedd** [comment]
wifislax ~ # wget http://fltk.org/pub/fltk/1.3.4/fltk-1.3.4-2-source.tar.gz
--2018-07-28 12:56:53--  http://fltk.org/pub/fltk/1.3.4/fltk-1.3.4-2-source.tar.gz
Resolving fltk.org (fltk.org)... 66.39.46.122
Connecting to fltk.org (fltk.org)|66.39.46.122|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5281263 (5.0M) [application/x-gzip]
Saving to: ‘fltk-1.3.4-2-source.tar.gz’

fltk-1.3.4-2-source.ta 100%[============================>]   5.04M  78.9KB/s    in 76s     

2018-07-28 12:58:10 (68.1 KB/s) - ‘fltk-1.3.4-2-source.tar.gz’ saved [5281263/5281263]

wifislax ~ # tar xzf fltk-1.3.4-2-source.tar.gz
wifislax ~ # cd fltk-1.3.4-2
wifislax fltk-1.3.4-2 # ./configure
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/fltk-1.3.4-2':
configure: error: C compiler cannot create executables
See `config.log' for more details
wifislax fltk-1.3.4-2 # make && make install
Makefile:19: makeinclude: No such file or directory
if test -f config.status; then \
        ./config.status --recheck; \
        ./config.status; \
else \
        ./configure; \
fi
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/fltk-1.3.4-2':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:95: recipe for target 'makeinclude' failed
make: *** [makeinclude] Error 77
wifislax fltk-1.3.4-2 # git clone https://github.com/aircrack-ng/aircrack-ng
Cloning into 'aircrack-ng'...
remote: Counting objects: 20304, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 20304 (delta 55), reused 57 (delta 36), pack-reused 20213
Receiving objects: 100% (20304/20304), 9.70 MiB | 25.00 KiB/s, done.
Resolving deltas: 100% (14146/14146), done.
Checking connectivity... done.
wifislax fltk-1.3.4-2 # ./autogen.sh
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/fltk-1.3.4-2':
configure: error: C compiler cannot create executables
See `config.log' for more details
wifislax fltk-1.3.4-2 # make && make install
Makefile:19: makeinclude: No such file or directory
if test -f config.status; then \
        ./config.status --recheck; \
        ./config.status; \
else \
        ./configure; \
fi
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/fltk-1.3.4-2':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:95: recipe for target 'makeinclude' failed
make: *** [makeinclude] Error 77
wifislax fltk-1.3.4-2 # git clone https://github.com/ChunshengZhao/feedingbottle
Cloning into 'feedingbottle'...
remote: Counting objects: 50, done.
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50
Unpacking objects: 100% (50/50), done.
Checking connectivity... done.
wifislax fltk-1.3.4-2 # cd feedingbottle
wifislax feedingbottle # fluid -c feedingbottle.fl
feedingbottle.fl:2: unknown version '1.0304'
wifislax feedingbottle # fltk-config --compile feedingbottle.cxx
g++ -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libdrm -I/usr/include/libpng16 -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o 'feedingbottle' 'feedingbottle.cxx' /usr/lib/libfltk.a -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
g++: error: /usr/lib/libfltk.a: No such file or directory
wifislax feedingbottle # ./feedingbottle
bash: ./feedingbottle: No such file or directory
wifislax feedingbottle #

So many errors. Maybe you can please give 32 (86) bit compiled version. I think it will run.

**Comment by ChunshengZhao** [comment]
http://www.mediafire.com/file/25rsmyz449g2csc/wifislax64-1.0-final.iso
Please use this version?

**Comment by oleedd** [comment]
Very strange. It doesn't work in VMware Workstation. But it works from BIOS.
But I have "can not into monitor mode" error for 2 my adapters which work in version 3.2.
This is how default Wifislax version 3.2 looks:
![snapshot1](https://user-images.githubusercontent.com/36125949/43355989-89a7fa78-9270-11e8-881c-024bbbb890d7.png)
But after changing feedingbottle file to version 3.38 the same error.

**Comment by ChunshengZhao** [comment]
Only support new versions of the aircrack-ng.
Old version is : mon0; new version is: wlan0mon.

**Comment by oleedd** [comment]
I see
mon0
wlan1
But not wlan0mon.

But I used this:
aircrack-ng
git clone https://github.com/aircrack-ng/aircrack-ng
./autogen.sh
make && make install

And there was the same error at the end.

**Comment by ChunshengZhao** [comment]
C compiler cannot create executables 
---Install gcc libc6-dev.

**Comment by ChunshengZhao** [comment]
This is not a problem with Feedingbottle, it is a problem with your system. I think you should go to the wifislax development team, Update aircrack and more software.
The system I tested is officially provided. If you use the system I am talking about to experiment, it will definitely succeed.

**Comment by oleedd** [comment]
What do you mean?
I have already compiled under BIOS using your steps (which work without errors under BIOS) and have the compiled version.
But the problem is "can not into monitor mode" error.

**Comment by ChunshengZhao** [comment]
**Only** support new versions of the aircrack-ng.

**Comment by oleedd** [comment]
Maybe there is a way to launch the newest aircrack-ng from a folder or a file without installing and after that to run compiled feedingbottle? Will be very good if possible.

**Comment by oleedd** [comment]
I downloaded that version from mediafire. But can't even run compiled feedingbottle there: permission denied. I don't need that version. My version is from their official site too. There is not only one iso on the site.

Maybe there is a way to launch the newest aircrack-ng from a folder or a file without installing and after that to run compiled feedingbottle? Will be very good if possible.

**Comment by ChunshengZhao** [comment]
Sorry, I think I have tried my best.

**Comment by oleedd** [comment]
I do directly the second aircrack-ng step because I already have the compiled version. And I have this:

wifislax ~ # git clone https://github.com/aircrack-ng/aircrack-ng
Cloning into 'aircrack-ng'...
remote: Counting objects: 20316, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 20316 (delta 64), reused 68 (delta 43), pack-reused 20213
Receiving objects: 100% (20316/20316), 9.70 MiB | 687.00 KiB/s, done.
Resolving deltas: 100% (14155/14155), done.
Checking connectivity... done.
wifislax ~ # ./autogen.sh
bash: ./autogen.sh: No such file or directory
wifislax ~ # make && make install
make: *** No targets specified and no makefile found.  Stop.

Something wrong with the second command "./autogen.sh".

**Comment by ChunshengZhao** [comment]
cd aircrack-ng

**Comment by oleedd** [comment]
Yes. It already works.
But I try to solve several things.
Is there a way to check by some command in which directories all aircrack-ng components are installed?

**Comment by ChunshengZhao** [comment]
The right thing to do is to support the new version of aircrack-ng instead of spending time on stale code.

**Comment by oleedd** [comment]
I updated. I have all the lastest version binary files. But any progress will not be saved in Wifislax. I can't install it every time.  So I need to know where all old aircrack-ng components are stored. Need a command for that.
If they are in \usr\bin\ I replace them with the new binaries. But it doesn't load monitor mode after that.

**Comment by oleedd** [comment]
Already found a way.

**Comment by ChunshengZhao** [comment]
I think you should consult the Wifislax development team on this issue.

**Comment by oleedd** [comment]
May just replacing binaries work? How do you think?

**Comment by ChunshengZhao** [comment]
Create an XMZ file and go to the Wifislax forum to learn it.

**Comment by oleedd** [comment]
I can't work with xzm archives.
If I have a folder with all aircrack-ng binaries (of the latest version). What command to use to install them from that folder?

**Comment by ChunshengZhao** [comment]
e,g, Line 204:
--if(system("airmon-ng check | awk '/Found/' > /tmp/FeedingBottle/airmon-ng_check.txt"));
++if(system("/yourfolder/airmon-ng check | awk '/Found/' > /tmp/FeedingBottle/airmon-ng_check.txt"));
All commands need to be replaced with your path.

**Comment by oleedd** [comment]
I see only 7 such strings. Yes?

**Comment by ChunshengZhao** [comment]
I am so busy in work. Please test it yourself.

**Comment by oleedd** [comment]
It is not urgent. But need to know exactly. Please check - 7 or not - later...

**Comment by ChunshengZhao** [comment]
204 221 1120 1592 1623 1643 1667 1672

**Comment by oleedd** [comment]
Ok. Thanks.
But I still need to know this.
What aircrack-ng components are need for loading adapters?
What command to use to know where are they installed? (It is impossible that there is no command to check this.)

**Comment by ChunshengZhao** [comment]
Sorry,I don’t know.

**Comment by oleedd** [comment]
I made xzm (of aircrack-ng 1.3). Adapters load well into monitore mode. But I have this error.

![](https://lh3.googleusercontent.com/-mLPjFjmoFjc/W2CdekKtlRI/AAAAAAAAAYY/PMJqAngNkl4TZ6UPIe3DLQHzL3QG4bPGACL0BGAYYCw/h768/2018-07-31.png)

**Comment by ChunshengZhao** [comment]
Run the program yourself and use the feedingbottle if it is successful.

**Comment by oleedd** [comment]
I don't know how to run it. It is just from xzm.

**Comment by ChunshengZhao** [comment]
Don't you know how to use this program? When you have finished xzm , the first thing to do is to check the correctness of the xzm. Now it may be a problem with your xzm. When you are sure that the xzm is working properly, use the feedingbottle program. What is the reason for your persistent efforts? Selling network cards with my program? If you are studying, I suggest you learn the basics.

**Comment by oleedd** [comment]
"Selling network cards with my program?" - I generally don't understand the idea.
"What is the reason for your persistent efforts?" - Just want to use the last version. If I spent time for this I don't want to give up. It is very unpleasant.
I don't have any special Linux knowledge and don't need it. Just want to make that programs will work.
I just converted txz into xzm (in Wifislax menu). After that it already passes loading monitor mode but not the second step.

**Comment by ChunshengZhao** [comment]
Support old versions of the aircrack-ng.

Line: 896
--strcat(m_strtemp," | grep \\"monitor\\" | awk '{print$9}' | awk '{split($0,a,\\"[])]\\");print a[2]}' > /tmp/FeedingBottle/IntoMonitorMode.txt");
++strcat(m_strtemp," | grep \\"monitor\\" | awk '{print$5}' | awk '{split($0,a,\\"[])]\\");print a[1]}' > /tmp/FeedingBottle/IntoMonitorMode.txt");

Line: 1120
--if(system("airmon-ng | grep [0-9] | awk '{print$2}' > /tmp/FeedingBottle/MonitorModeDevice.txt"));
++if(system("airmon-ng | grep [0-9] | awk '{print$1}' > /tmp/FeedingBottle/MonitorModeDevice.txt"));

**Comment by oleedd** [comment]
I installed the lastest fltk. But I have this errors.

wifislax feedingbottle-master # fltk-config --compile feedingbottle.cxx
g++ -I/usr/local/include -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o 'feedingbottle' 'feedingbottle.cxx' /usr/local/lib/libfltk.a -lXrender -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
feedingbottle.cxx: In function ‘void IntoMonitorMode()’:
feedingbottle.cxx:1152:38: error: expected ‘)’ before ‘monitor’
           strcat(m_strtemp," | grep "monitor" | awk '{print$5}' | awk '{split($
                                      ^
feedingbottle.cxx:1152:88: error: expected ‘;’ before ‘]’ token
 strtemp," | grep "monitor" | awk '{print$5}' | awk '{split($0,a,"[])]");print a

**Comment by ChunshengZhao** [comment]
Just need to modify the three characters, if this is not correct, then I can't help you,

**Comment by oleedd** [comment]
The problem is in these strings.

feedingbottle.cxx:1152:38: error: expected ‘)’ before ‘monitor’
strcat(m_strtemp," | grep "monitor" | awk '{print$5}' | awk '{split($
^
feedingbottle.cxx:1152:88: error: expected ‘;’ before ‘]’ token
strtemp," | grep "monitor" | awk '{print$5}' | awk '{split($0,a,"[])]");print a

**Comment by ChunshengZhao** [comment]
[feedingbottle.zip](https://github.com/ChunshengZhao/feedingbottle/files/2248898/feedingbottle.zip)

**Comment by oleedd** [comment]
Yes. It already works. Thank you.
Will it work worse with old aircrack-ng in comparison with the latest version?

**Comment by ChunshengZhao** [comment]
You can view aircrack-ng’s change log .

**Comment by oleedd** [comment]
Please suggest. What Linux module (component) is need for opening by double click such binary files as feedingbottle?

**Comment by ChunshengZhao** [comment]
My English is not good, I suggest you learn the basics of linux. good luck.

**Comment by oleedd** [comment]
If to double click feedingbottle (compiled file) then it runs. But what component of Linux (what to install) is need for that? I have another system but there is the only one problem that it doesn't open after double click (any such files). What component to install? Please help.

**Comment by oleedd** [comment]
???

**Comment by oleedd** [comment]
I wait for a reply.

**Comment by oleedd** [comment]
Still wait(((

**Comment by oleedd** [comment]
Please.
