### ISSUE TITLE
kali 2020.4 FeedingBottle所有字符变成方块

### ISSUE THREAD

**Issue by longhuan1999** [ChunshengZhao/feedingbottle#2]
kali 2020.4 zh_CN.UTF-8 下安装 FeedingBottle ，打开后 FeedingBottle 所有字符变成方块

**Comment by longhuan1999** [comment]
抱歉，是我自己的问题。
kali 2020.4 zh_CN.UTF-8 xfce桌面 需要安装一下字体：
sudo apt-get install ttf-wqy-zenhei
并且安装一下xterm：
sudo apt install xterm -y

**Comment by ChunshengZhao** [comment]
> 
> 
> 抱歉，是我自己的问题。
> kali 2020.4 zh_CN.UTF-8 xfce桌面 需要安装一下字体：
> sudo apt-get install ttf-wqy-zenhei
> 并且安装一下xterm：
> sudo apt install xterm -y

感谢分享。
